# Generated by Django 4.2.13 on 2024-06-18 21:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vhdlGenerator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='expressions',
            new_name='Expression',
        ),
    ]
