# Generated by Django 4.2.13 on 2024-06-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhdlGenerator', '0002_rename_expressions_expression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='status',
            field=models.CharField(max_length=1),
        ),
    ]
