from ComponentBases.ComponentCommonMethods import ComponentCommonMethods
from ComponentBases.port import Port

    #Compilado
    #Testado
class Sigmoid(ComponentCommonMethods):
    def __init__(self, dataWidth = 8):
        self.dataWidth = dataWidth
        self.createComponent()
        
    
    def createComponent(self):
        self.startInstance()
        self.minimalComponentFileName = f"Sigmoid_{self.dataWidth}dw"
        self.portMap =   { 'in': [
                                Port('i_X',f"std_logic_vector({self.dataWidth-1} downto 0)"),
                                Port('i_CLK','std_logic')
                                ],
                            'out': [ Port('o_Y',f"std_logic_vector({self.dataWidth-1} downto 0)")]
                    }
        self.addArrayTypeOnArchitecture(name='lut_array',datatype=f'signed({self.dataWidth-1} downto 0)',size=255)
        self.addInternalConstant(name='sigmoid_lut', dataType=f"lut_array", 
                                 value=f'''(0   => to_signed(0,{self.dataWidth}),
         1   => to_signed(0,{self.dataWidth}),
         2   => to_signed(0,{self.dataWidth}),
         3   => to_signed(0,{self.dataWidth}),
         4   => to_signed(0,{self.dataWidth}),
         5   => to_signed(0,{self.dataWidth}),
         6   => to_signed(0,{self.dataWidth}),
         7   => to_signed(0,{self.dataWidth}),
         8   => to_signed(0,{self.dataWidth}),
         9   => to_signed(0,{self.dataWidth}),
         10  => to_signed(0,{self.dataWidth}),
         11  => to_signed(0,{self.dataWidth}),
         12  => to_signed(0,{self.dataWidth}),
         13  => to_signed(0,{self.dataWidth}),
         14  => to_signed(0,{self.dataWidth}),
         15  => to_signed(0,{self.dataWidth}),
         16  => to_signed(0,{self.dataWidth}),
         17  => to_signed(0,{self.dataWidth}),
         18  => to_signed(0,{self.dataWidth}),
         19  => to_signed(0,{self.dataWidth}),
         20  => to_signed(0,{self.dataWidth}),
         21  => to_signed(0,{self.dataWidth}),
         22  => to_signed(0,{self.dataWidth}),
         23  => to_signed(0,{self.dataWidth}),
         24  => to_signed(0,{self.dataWidth}),
         25  => to_signed(0,{self.dataWidth}),
         26  => to_signed(0,{self.dataWidth}),
         27  => to_signed(0,{self.dataWidth}),
         28  => to_signed(0,{self.dataWidth}),
         29  => to_signed(1,{self.dataWidth}),
         30  => to_signed(1,{self.dataWidth}),
         31  => to_signed(1,{self.dataWidth}),
         32  => to_signed(1,{self.dataWidth}),
         33  => to_signed(1,{self.dataWidth}),
         34  => to_signed(1,{self.dataWidth}),
         35  => to_signed(1,{self.dataWidth}),
         36  => to_signed(1,{self.dataWidth}),
         37  => to_signed(2,{self.dataWidth}),
         38  => to_signed(2,{self.dataWidth}),
         39  => to_signed(2,{self.dataWidth}),
         40  => to_signed(2,{self.dataWidth}),
         41  => to_signed(2,{self.dataWidth}),
         42  => to_signed(2,{self.dataWidth}),
         43  => to_signed(2,{self.dataWidth}),
         44  => to_signed(3,{self.dataWidth}),
         45  => to_signed(3,{self.dataWidth}),
         46  => to_signed(3,{self.dataWidth}),
         47  => to_signed(3,{self.dataWidth}),
         48  => to_signed(3,{self.dataWidth}),
         49  => to_signed(3,{self.dataWidth}),
         50  => to_signed(3,{self.dataWidth}),
         51  => to_signed(4,{self.dataWidth}),
         52  => to_signed(4,{self.dataWidth}),
         53  => to_signed(4,{self.dataWidth}),
         54  => to_signed(4,{self.dataWidth}),
         55  => to_signed(4,{self.dataWidth}),
         56  => to_signed(4,{self.dataWidth}),
         57  => to_signed(4,{self.dataWidth}),
         58  => to_signed(5,{self.dataWidth}),
         59  => to_signed(5,{self.dataWidth}),
         60  => to_signed(5,{self.dataWidth}),
         61  => to_signed(5,{self.dataWidth}),
         62  => to_signed(5,{self.dataWidth}),
         63  => to_signed(5,{self.dataWidth}),
         64  => to_signed(6,{self.dataWidth}),
         65  => to_signed(6,{self.dataWidth}),
         66  => to_signed(6,{self.dataWidth}),
         67  => to_signed(6,{self.dataWidth}),
         68  => to_signed(6,{self.dataWidth}),
         69  => to_signed(6,{self.dataWidth}),
         70  => to_signed(6,{self.dataWidth}),
         71  => to_signed(7,{self.dataWidth}),
         72  => to_signed(7,{self.dataWidth}),
         73  => to_signed(7,{self.dataWidth}),
         74  => to_signed(7,{self.dataWidth}),
         75  => to_signed(7,{self.dataWidth}),
         76  => to_signed(7,{self.dataWidth}),
         77  => to_signed(7,{self.dataWidth}),
         78  => to_signed(8,{self.dataWidth}),
         79  => to_signed(8,{self.dataWidth}),
         80  => to_signed(8,{self.dataWidth}),
         81  => to_signed(8,{self.dataWidth}),
         82  => to_signed(8,{self.dataWidth}),
         83  => to_signed(8,{self.dataWidth}),
         84  => to_signed(8,{self.dataWidth}),
         85  => to_signed(9,{self.dataWidth}),
         86  => to_signed(9,{self.dataWidth}),
         87  => to_signed(9,{self.dataWidth}),
         88  => to_signed(9,{self.dataWidth}),
         89  => to_signed(9,{self.dataWidth}),
         90  => to_signed(9,{self.dataWidth}),
         91  => to_signed(10,{self.dataWidth}),
         92  => to_signed(10,{self.dataWidth}),
         93  => to_signed(10,{self.dataWidth}),
         94  => to_signed(10,{self.dataWidth}),
         95  => to_signed(10,{self.dataWidth}),
         96  => to_signed(10,{self.dataWidth}),
         97  => to_signed(11,{self.dataWidth}),
         98  => to_signed(11,{self.dataWidth}),
         99  => to_signed(11,{self.dataWidth}),
         100 => to_signed(11,{self.dataWidth}),
         101 => to_signed(11,{self.dataWidth}),
         102 => to_signed(11,{self.dataWidth}),
         103 => to_signed(12,{self.dataWidth}),
         104 => to_signed(12,{self.dataWidth}),
         105 => to_signed(12,{self.dataWidth}),
         106 => to_signed(12,{self.dataWidth}),
         107 => to_signed(12,{self.dataWidth}),
         108 => to_signed(12,{self.dataWidth}),
         109 => to_signed(13,{self.dataWidth}),
         110 => to_signed(13,{self.dataWidth}),
         111 => to_signed(13,{self.dataWidth}),
         112 => to_signed(13,{self.dataWidth}),
         113 => to_signed(13,{self.dataWidth}),
         114 => to_signed(13,{self.dataWidth}),
         115 => to_signed(14,{self.dataWidth}),
         116 => to_signed(14,{self.dataWidth}),
         117 => to_signed(14,{self.dataWidth}),
         118 => to_signed(14,{self.dataWidth}),
         119 => to_signed(14,{self.dataWidth}),
         120 => to_signed(14,{self.dataWidth}),
         121 => to_signed(15,{self.dataWidth}),
         122 => to_signed(15,{self.dataWidth}),
         123 => to_signed(15,{self.dataWidth}),
         124 => to_signed(15,{self.dataWidth}),
         125 => to_signed(15,{self.dataWidth}),
         126 => to_signed(15,{self.dataWidth}),
         127 => to_signed(16,{self.dataWidth}),
         128 => to_signed(17,{self.dataWidth}),
         129 => to_signed(18,{self.dataWidth}),
         130 => to_signed(19,{self.dataWidth}),
         131 => to_signed(20,{self.dataWidth}),
         132 => to_signed(21,{self.dataWidth}),
         133 => to_signed(22,{self.dataWidth}),
         134 => to_signed(23,{self.dataWidth}),
         135 => to_signed(24,{self.dataWidth}),
         136 => to_signed(25,{self.dataWidth}),
         137 => to_signed(26,{self.dataWidth}),
         138 => to_signed(27,{self.dataWidth}),
         139 => to_signed(28,{self.dataWidth}),
         140 => to_signed(29,{self.dataWidth}),
         141 => to_signed(30,{self.dataWidth}),
         142 => to_signed(31,{self.dataWidth}),
         143 => to_signed(32,{self.dataWidth}),
         144 => to_signed(33,{self.dataWidth}),
         145 => to_signed(34,{self.dataWidth}),
         146 => to_signed(35,{self.dataWidth}),
         147 => to_signed(36,{self.dataWidth}),
         148 => to_signed(37,{self.dataWidth}),
         149 => to_signed(38,{self.dataWidth}),
         150 => to_signed(39,{self.dataWidth}),
         151 => to_signed(40,{self.dataWidth}),
         152 => to_signed(41,{self.dataWidth}),
         153 => to_signed(42,{self.dataWidth}),
         154 => to_signed(43,{self.dataWidth}),
         155 => to_signed(44,{self.dataWidth}),
         156 => to_signed(45,{self.dataWidth}),
         157 => to_signed(46,{self.dataWidth}),
         158 => to_signed(47,{self.dataWidth}),
         159 => to_signed(48,{self.dataWidth}),
         160 => to_signed(49,{self.dataWidth}),
         161 => to_signed(50,{self.dataWidth}),
         162 => to_signed(51,{self.dataWidth}),
         163 => to_signed(52,{self.dataWidth}),
         164 => to_signed(53,{self.dataWidth}),
         165 => to_signed(54,{self.dataWidth}),
         166 => to_signed(55,{self.dataWidth}),
         167 => to_signed(56,{self.dataWidth}),
         168 => to_signed(57,{self.dataWidth}),
         169 => to_signed(58,{self.dataWidth}),
         170 => to_signed(59,{self.dataWidth}),
         171 => to_signed(60,{self.dataWidth}),
         172 => to_signed(61,{self.dataWidth}),
         173 => to_signed(62,{self.dataWidth}),
         174 => to_signed(63,{self.dataWidth}),
         175 => to_signed(64,{self.dataWidth}),
         176 => to_signed(65,{self.dataWidth}),
         177 => to_signed(66,{self.dataWidth}),
         178 => to_signed(67,{self.dataWidth}),
         179 => to_signed(68,{self.dataWidth}),
         180 => to_signed(69,{self.dataWidth}),
         181 => to_signed(70,{self.dataWidth}),
         182 => to_signed(71,{self.dataWidth}),
         183 => to_signed(72,{self.dataWidth}),
         184 => to_signed(73,{self.dataWidth}),
         185 => to_signed(74,{self.dataWidth}),
         186 => to_signed(75,{self.dataWidth}),
         187 => to_signed(76,{self.dataWidth}),
         188 => to_signed(77,{self.dataWidth}),
         189 => to_signed(78,{self.dataWidth}),
         190 => to_signed(79,{self.dataWidth}),
         191 => to_signed(80,{self.dataWidth}),
         192 => to_signed(81,{self.dataWidth}),
         193 => to_signed(82,{self.dataWidth}),
         194 => to_signed(83,{self.dataWidth}),
         195 => to_signed(84,{self.dataWidth}),
         196 => to_signed(85,{self.dataWidth}),
         197 => to_signed(86,{self.dataWidth}),
         198 => to_signed(87,{self.dataWidth}),
         199 => to_signed(88,{self.dataWidth}),
         200 => to_signed(89,{self.dataWidth}),
         201 => to_signed(90,{self.dataWidth}),
         202 => to_signed(91,{self.dataWidth}),
         203 => to_signed(92,{self.dataWidth}),
         204 => to_signed(93,{self.dataWidth}),
         205 => to_signed(94,{self.dataWidth}),
         206 => to_signed(95,{self.dataWidth}),
         207 => to_signed(96,{self.dataWidth}),
         208 => to_signed(97,{self.dataWidth}),
         209 => to_signed(98,{self.dataWidth}),
         210 => to_signed(99,{self.dataWidth}),
         211 => to_signed(100,{self.dataWidth}),
         212 => to_signed(101,{self.dataWidth}),
         213 => to_signed(102,{self.dataWidth}),
         214 => to_signed(103,{self.dataWidth}),
         215 => to_signed(104,{self.dataWidth}),
         216 => to_signed(105,{self.dataWidth}),
         217 => to_signed(106,{self.dataWidth}),
         218 => to_signed(107,{self.dataWidth}),
         219 => to_signed(108,{self.dataWidth}),
         220 => to_signed(109,{self.dataWidth}),
         221 => to_signed(110,{self.dataWidth}),
         222 => to_signed(111,{self.dataWidth}),
         223 => to_signed(112,{self.dataWidth}),
         224 => to_signed(113,{self.dataWidth}),
         225 => to_signed(114,{self.dataWidth}),
         226 => to_signed(115,{self.dataWidth}),
         227 => to_signed(116,{self.dataWidth}),
         228 => to_signed(117,{self.dataWidth}),
         229 => to_signed(118,{self.dataWidth}),
         230 => to_signed(119,{self.dataWidth}),
         231 => to_signed(120,{self.dataWidth}),
         232 => to_signed(121,{self.dataWidth}),
         233 => to_signed(122,{self.dataWidth}),
         234 => to_signed(123,{self.dataWidth}),
         235 => to_signed(124,{self.dataWidth}),
         236 => to_signed(125,{self.dataWidth}),
         237 => to_signed(126,{self.dataWidth}),
         238 => to_signed(127,{self.dataWidth}),
         239 => to_signed(128,{self.dataWidth}),
         240 => to_signed(129,{self.dataWidth}),
         241 => to_signed(130,{self.dataWidth}),
         242 => to_signed(131,{self.dataWidth}),
         243 => to_signed(132,{self.dataWidth}),
         244 => to_signed(133,{self.dataWidth}),
         245 => to_signed(134,{self.dataWidth}),
         246 => to_signed(135,{self.dataWidth}),
         247 => to_signed(136,{self.dataWidth}),
         248 => to_signed(137,{self.dataWidth}),
         249 => to_signed(138,{self.dataWidth}),
         250 => to_signed(139,{self.dataWidth}),
         251 => to_signed(140,{self.dataWidth}),
         252 => to_signed(141,{self.dataWidth}),
         253 => to_signed(142,{self.dataWidth}),
         254 => to_signed(143,{self.dataWidth}))
''')

        self.internalOperations = f"""
    process(i_CLK)
        variable x_signed     : signed(7 downto 0);
        variable mapped_value : integer range 0 to 254;
    begin
        if falling_edge(i_CLK) then
            x_signed := signed(i_X); -- Converte entrada para signed

            if x_signed < to_signed(-8, 8) then
                mapped_value := 0;
            elsif x_signed > to_signed(8, 8) then
                mapped_value := 254;
            else
                mapped_value :=  (to_integer(x_signed) + 8 )/16 *254;
            end if;

            -- Retorna o valor da LUT correspondente
            o_Y <= std_logic_vector(sigmoid_lut(mapped_value));
        end if;
    end process;
        """
        self.OutputEntityAndArchitectureFile()